use async_trait::async_trait;
use std::sync::Arc;

/// Resolves NATS authentication for the agent's connection (design: NATS WebSocket +
/// pluggable auth §2). Mirrors the IdentityProvider pattern: a simple default lives here in
/// Core; richer composition (e.g. reusing an AAD identity) happens in a host's main.rs.
#[async_trait]
pub trait NatsAuthProvider: Send + Sync {
    async fn connect_options(&self) -> anyhow::Result<async_nats::ConnectOptions>;
}

/// Authenticates using a standard NATS .creds file (user JWT + NKey seed) (design §3).
pub struct CredsFileAuth {
    pub path: String,
}

#[async_trait]
impl NatsAuthProvider for CredsFileAuth {
    async fn connect_options(&self) -> anyhow::Result<async_nats::ConnectOptions> {
        tracing::debug!(path = %self.path, "nats auth [creds-file]: loading");
        let opts = async_nats::ConnectOptions::new().credentials_file(&self.path).await?;
        tracing::debug!("nats auth [creds-file]: loaded ok");
        Ok(opts)
    }
}

/// Resolves a fresh AAD access token for the scope needed to call the external NATS auth
/// service. Kept decoupled from AAD/device-code specifics (implemented by AadTokenProvider in
/// identity.rs) — mirrors how the C# provider takes a `Func<CancellationToken, Task<string>>`.
#[async_trait]
pub trait AccessTokenProvider: Send + Sync {
    async fn access_token(&self) -> anyhow::Result<String>;
}

#[derive(serde::Deserialize)]
struct JwtResponse {
    jwt: String,
}

struct ExternalAuthServiceAuthInner {
    auth_service_url: String,
    access_token_provider: Arc<dyn AccessTokenProvider>,
    http: reqwest::Client,
    seed: String,
    public_key: String,
}

impl ExternalAuthServiceAuthInner {
    async fn fetch_jwt(&self, aad_token: &str) -> anyhow::Result<String> {
        tracing::debug!(url = %self.auth_service_url, "nats auth [external-service]: requesting jwt");
        let response = self
            .http
            .post(&self.auth_service_url)
            .bearer_auth(aad_token)
            .json(&serde_json::json!({ "nkeyPublicKey": self.public_key }))
            .send()
            .await?;
        if !response.status().is_success() {
            tracing::debug!(status = %response.status(), "nats auth [external-service]: request failed");
            anyhow::bail!("NATS auth service returned {}", response.status());
        }
        let jwt = response.json::<JwtResponse>().await?.jwt;
        tracing::debug!("nats auth [external-service]: jwt received");
        Ok(jwt)
    }

    /// Called on every connect/reconnect attempt (design §4): refetches the AAD token and JWT
    /// each time, so token refresh needs no timer or reconnect-and-swap logic.
    async fn fetch_auth(&self, nonce: &[u8]) -> anyhow::Result<async_nats::Auth> {
        tracing::debug!("nats auth [external-service]: callback invoked (connect/reconnect)");
        // Spawned rather than awaited inline: `AccessTokenProvider::access_token` is generated by
        // `#[async_trait]` as `Pin<Box<dyn Future<..> + Send>>` (no `Sync`), so awaiting it
        // directly here would make this whole async fn's future non-`Sync` — and
        // `ConnectOptions::with_auth_callback` requires `Fut: Future<..> + Send + Sync`. Running
        // it on a spawned task keeps the only cross-await state a `JoinHandle`, which is Sync.
        let access_token_provider = self.access_token_provider.clone();
        let aad_token =
            tokio::spawn(async move { access_token_provider.access_token().await }).await??;
        tracing::debug!("nats auth [external-service]: aad token acquired");
        let jwt = self.fetch_jwt(&aad_token).await?;
        let key_pair = nkeys::KeyPair::from_seed(&self.seed).map_err(|e| anyhow::anyhow!(e.to_string()))?;
        let signature = key_pair.sign(nonce).map_err(|e| anyhow::anyhow!(e.to_string()))?;
        tracing::debug!("nats auth [external-service]: nonce signed, auth ready");
        let mut auth = async_nats::Auth::new();
        auth.jwt = Some(jwt);
        auth.signature = Some(signature);
        Ok(auth)
    }
}

/// Authenticates NATS via an external HTTPS auth service, reusing the agent's AAD identity
/// (design §4). The NKey seed is generated once per process and held in memory only — never
/// persisted or transmitted; only its public key is sent to the auth service.
pub struct ExternalAuthServiceAuth(Arc<ExternalAuthServiceAuthInner>);

impl ExternalAuthServiceAuth {
    pub fn new(
        auth_service_url: String,
        access_token_provider: Arc<dyn AccessTokenProvider>,
    ) -> anyhow::Result<Self> {
        let key_pair = nkeys::KeyPair::new(nkeys::KeyPairType::User);
        let http = reqwest::Client::builder().timeout(std::time::Duration::from_secs(10)).build()?;
        Ok(Self(Arc::new(ExternalAuthServiceAuthInner {
            auth_service_url,
            access_token_provider,
            http,
            seed: key_pair.seed().map_err(|e| anyhow::anyhow!(e.to_string()))?,
            public_key: key_pair.public_key(),
        })))
    }

    pub fn public_key(&self) -> &str {
        &self.0.public_key
    }

    /// Exposed directly (rather than only reachable through `connect_options`'s closure) so it
    /// can be unit tested without a real NATS server — see Global Constraints on why
    /// `ConnectOptions`'s callback field can't be inspected/invoked externally.
    pub async fn fetch_auth(&self, nonce: &[u8]) -> anyhow::Result<async_nats::Auth> {
        self.0.fetch_auth(nonce).await
    }
}

#[async_trait]
impl NatsAuthProvider for ExternalAuthServiceAuth {
    async fn connect_options(&self) -> anyhow::Result<async_nats::ConnectOptions> {
        let inner = self.0.clone();
        Ok(async_nats::ConnectOptions::with_auth_callback(move |nonce| {
            let inner = inner.clone();
            async move { inner.fetch_auth(&nonce).await.map_err(async_nats::AuthError::new) }
        }))
    }
}

/// Presence-based selection inputs for which NatsAuthProvider to use, mirroring how
/// NOTIFY_AAD_CLIENT_ID selects an identity provider (design §4: startup wiring). Pure and
/// testable on any platform; actual provider construction (which needs DeviceCodeIdentity /
/// AadTokenProvider wiring) happens in each host's main.rs.
pub struct NatsAuthConfig {
    pub auth_service_url: Option<String>,
    pub auth_service_scope: Option<String>,
    pub has_aad_identity: bool,
}

pub fn validate_auth_service_config(config: &NatsAuthConfig) -> anyhow::Result<()> {
    let Some(url) = &config.auth_service_url else {
        return Ok(());
    };
    anyhow::ensure!(
        config.has_aad_identity,
        "NOTIFY_NATS_AUTH_SERVICE_URL requires NOTIFY_AAD_CLIENT_ID (external NATS auth reuses AAD identity)"
    );
    anyhow::ensure!(
        config.auth_service_scope.is_some(),
        "NOTIFY_NATS_AUTH_SERVICE_URL requires NOTIFY_NATS_AUTH_SERVICE_SCOPE"
    );
    anyhow::ensure!(
        url.starts_with("https://"),
        "NOTIFY_NATS_AUTH_SERVICE_URL must use https (the AAD bearer token would otherwise be sent in cleartext)"
    );
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use tokio::io::{AsyncReadExt, AsyncWriteExt};

    fn write_temp_creds(seed: &str) -> std::path::PathBuf {
        let path = std::env::temp_dir().join(format!(
            "notify-agent-test-{}.creds",
            std::time::SystemTime::now().duration_since(std::time::UNIX_EPOCH).unwrap().as_nanos()
        ));
        let contents = format!(
            "-----BEGIN NATS USER JWT-----\nfake.jwt.value\n------END NATS USER JWT------\n\n\
             -----BEGIN USER NKEY SEED-----\n{seed}\n------END USER NKEY SEED------\n"
        );
        std::fs::write(&path, contents).unwrap();
        path
    }

    #[tokio::test]
    async fn creds_file_auth_builds_connect_options_from_a_valid_file() {
        let seed = nkeys::KeyPair::new(nkeys::KeyPairType::User).seed().unwrap();
        let path = write_temp_creds(&seed);

        let result = CredsFileAuth { path: path.to_string_lossy().into_owned() }.connect_options().await;

        std::fs::remove_file(&path).ok();
        assert!(result.is_ok(), "expected a valid creds file to parse: {result:?}");
    }

    #[tokio::test]
    async fn creds_file_auth_fails_on_missing_file() {
        let provider = CredsFileAuth { path: "/nonexistent/path.creds".into() };
        assert!(provider.connect_options().await.is_err());
    }

    struct FixedToken(String);

    #[async_trait]
    impl AccessTokenProvider for FixedToken {
        async fn access_token(&self) -> anyhow::Result<String> {
            Ok(self.0.clone())
        }
    }

    /// Minimal one-shot HTTP/1.1 stub: accepts one connection, writes the given response with
    /// `Connection: close` (so reqwest reads the body until EOF, no Content-Length bookkeeping
    /// needed), and hands back the raw request bytes it received for assertions.
    async fn stub_http_once(response_status_and_body: &'static str) -> (String, tokio::task::JoinHandle<Vec<u8>>) {
        let listener = tokio::net::TcpListener::bind("127.0.0.1:0").await.unwrap();
        let addr = listener.local_addr().unwrap();
        let handle = tokio::spawn(async move {
            let (mut socket, _) = listener.accept().await.unwrap();
            let mut buf = vec![0u8; 8192];
            let n = socket.read(&mut buf).await.unwrap();
            socket.write_all(response_status_and_body.as_bytes()).await.unwrap();
            socket.shutdown().await.ok();
            buf[..n].to_vec()
        });
        (format!("http://{addr}"), handle)
    }

    #[tokio::test]
    async fn fetch_auth_posts_public_key_and_bearer_token_then_signs_nonce() {
        let (url, handle) = stub_http_once(
            "HTTP/1.1 200 OK\r\ncontent-type: application/json\r\nconnection: close\r\n\r\n{\"jwt\":\"jwt-1\"}",
        )
        .await;
        let provider =
            ExternalAuthServiceAuth::new(url, Arc::new(FixedToken("aad-token-1".into()))).unwrap();

        let auth = provider.fetch_auth(b"the-nonce").await.unwrap();

        let request = String::from_utf8(handle.await.unwrap()).unwrap().to_lowercase();
        assert!(request.contains("authorization: bearer aad-token-1"));
        assert!(request.contains(&provider.public_key().to_lowercase()));
        assert_eq!(auth.jwt.as_deref(), Some("jwt-1"));
        assert!(auth.signature.is_some());
    }

    #[tokio::test]
    async fn fetch_auth_reuses_the_same_nkey_seed_across_calls() {
        let make_response = || {
            "HTTP/1.1 200 OK\r\ncontent-type: application/json\r\nconnection: close\r\n\r\n{\"jwt\":\"same-jwt\"}"
        };
        let (url1, _h1) = stub_http_once(make_response()).await;
        let provider = ExternalAuthServiceAuth::new(url1, Arc::new(FixedToken("t".into()))).unwrap();
        let key1 = provider.public_key().to_string();

        // A second connect/reconnect attempt against a fresh stub must reuse the same NKey.
        let auth1 = provider.fetch_auth(b"nonce-1").await.unwrap();
        let key2 = provider.public_key().to_string();

        assert_eq!(key1, key2);
        assert!(auth1.signature.is_some());
    }

    #[tokio::test]
    async fn fetch_auth_fails_on_non_success_status() {
        let (url, _handle) =
            stub_http_once("HTTP/1.1 401 Unauthorized\r\nconnection: close\r\n\r\n").await;
        let provider = ExternalAuthServiceAuth::new(url, Arc::new(FixedToken("t".into()))).unwrap();

        assert!(provider.fetch_auth(b"nonce").await.is_err());
    }

    #[tokio::test]
    async fn fetch_auth_fails_when_response_has_no_jwt() {
        let (url, _handle) = stub_http_once(
            "HTTP/1.1 200 OK\r\ncontent-type: application/json\r\nconnection: close\r\n\r\n{}",
        )
        .await;
        let provider = ExternalAuthServiceAuth::new(url, Arc::new(FixedToken("t".into()))).unwrap();

        assert!(provider.fetch_auth(b"nonce").await.is_err());
    }

    #[test]
    fn validate_auth_service_config_ok_when_url_not_set() {
        let cfg = NatsAuthConfig { auth_service_url: None, auth_service_scope: None, has_aad_identity: false };
        assert!(validate_auth_service_config(&cfg).is_ok());
    }

    #[test]
    fn validate_auth_service_config_requires_aad_identity() {
        let cfg = NatsAuthConfig {
            auth_service_url: Some("https://auth.example.com".into()),
            auth_service_scope: Some("api://x/Nats.Connect".into()),
            has_aad_identity: false,
        };
        assert!(validate_auth_service_config(&cfg).is_err());
    }

    #[test]
    fn validate_auth_service_config_requires_scope() {
        let cfg = NatsAuthConfig {
            auth_service_url: Some("https://auth.example.com".into()),
            auth_service_scope: None,
            has_aad_identity: true,
        };
        assert!(validate_auth_service_config(&cfg).is_err());
    }

    #[test]
    fn validate_auth_service_config_requires_https() {
        let cfg = NatsAuthConfig {
            auth_service_url: Some("http://auth.example.com".into()),
            auth_service_scope: Some("api://x/Nats.Connect".into()),
            has_aad_identity: true,
        };
        let err = validate_auth_service_config(&cfg).unwrap_err();
        assert!(err.to_string().to_lowercase().contains("https"));
    }

    #[test]
    fn validate_auth_service_config_ok_when_fully_configured() {
        let cfg = NatsAuthConfig {
            auth_service_url: Some("https://auth.example.com".into()),
            auth_service_scope: Some("api://x/Nats.Connect".into()),
            has_aad_identity: true,
        };
        assert!(validate_auth_service_config(&cfg).is_ok());
    }
}
